language: go
sudo: false

go:
  - 1.11.x

env:
  global:
    - CGO_ENABLED=0
    - GO111MODULE=on

install:
  - go mod download

script:
  - go test
  - GOARCH=amd64 GOOS=linux  go build boilr.go && tar czvf boilr-$VERSION-linux_amd64.tgz boilr
  - GOARCH=386   GOOS=linux  go build boilr.go && tar czvf boilr-$VERSION-linux_386.tgz boilr
  - GOARCH=amd64 GOOS=darwin go build boilr.go && tar czvf boilr-$VERSION-darwin_amd64.tgz boilr
  - GOARCH=386   GOOS=darwin go build boilr.go && tar czvf boilr-$VERSION-darwin_386.tgz boilr


deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

notifications:
  email:
    on_success: change
    on_failure: always
