language: go
sudo: false
matrix:
  include:
  - go: 1.x
    env: VERSION=0.4.0

before_deploy:
- GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build boilr.go  && tar czvf boilr-$VERSION-linux_amd64.tgz boilr
- GOARCH=386   GOOS=linux CGO_ENABLED=0 go build boilr.go  && tar czvf boilr-$VERSION-linux_386.tgz boilr

- GOARCH=amd64 GOOS=darwin CGO_ENABLED=0 go build boilr.go && tar czvf boilr-$VERSION-darwin_amd64.tgz boilr
- GOARCH=386   GOOS=darwin CGO_ENABLED=0 go build boilr.go && tar czvf boilr-$VERSION-darwin_386.tgz boilr

deploy:
  provider: releases
  api_key:
    secure: Se4pyaMF04cgTnTi90bA2poDh1H5cEBYt0JOFrgQfl++6LGdSo2iSULg8EktvoJPwuo2uD6ywUvU67W/V8186KriE4S6mwdcOIFFNPoX4qDxoTNxa+KzYH8irIblTbqxYKWKMz8SYE+DzmOyGWkvbmUB8O6KXaNd6Lx00CmdqvJJZ1ORdsywY5b+KZbnWX59Hdkx+Jun2PeMAVOGXfWLsws9stb1+8a4lQvBup47xlin5sN7g/QOEj1FEObAr47a4ttJURt+h99UIr3av7KCxK1ukYMPQlVhTMWhLTroncOZw7oq55JIS1iasRz0cF7JjUKSzHoUxe4ivSFQmdwBAD9LpghEelQytj0ZhSAf5ltzxQZtHpjjqbJcXb7Vf+aEPMWZpWQB8cGC9cMQbrSrn0ggSYOzV9weI62euGpjbFUfECly+sV//8oWp71+9f8sr9/wsAF8I+ygJnu74v4/KfUhKXY+19SOe6SLU+kXC1V/4Mj76C8XTBVXwPjcrRpY2H98QsKshlbFnRVzE7XBGOP8aAhwhe4KE3+JNWwQtBbbhcZEGu5QnXlUawXfFb5OFV+PPxerwXgcTfiN9X3qezQ/R8g9p1jTIZi5VVPXvuu4CU28EbtVi5MUPDa66Vg6EUN+HOp9u2e0uuTABt5Xx/jNvfI1lMTUPEm2ZFibfwc=
  file:
    - install
    - boilr-$VERSION-darwin_386.tgz
    - boilr-$VERSION-darwin_amd64.tgz
    - boilr-$VERSION-linux_386.tgz
    - boilr-$VERSION-linux_amd64.tgz
  skip_cleanup: true
  on:
    repo: Ilyes512/boilr
    branch: master
    tags: true

notifications:
  email:
    on_success: change
    on_failure: always
