name: Build Boilr

on:
  pull_request:
  push:
    branches: [main]

permissions: read-all

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Force fetch tags
        run: git fetch --force --tags
      - name: Setup Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: stable
          check-latest: true
      - name: Use Goreleaser for building Boilr
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          distribution: goreleaser
          version: '~> v2'
          args: build --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
