name: Release Boilr

on:
  push:
    tags: ['*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Force fetch tags
        run: git fetch --force --tags
      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: stable
          check-latest: true
      - name: Use Goreleaser to release Boilr
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
